### ISSUE TITLE
Relation to mpv.el

### ISSUE THREAD

**Issue by SylvianHemus** [isamert/empv.el#18]
Am new to this space, someone made a interesting library for emacs that seems to transcode and notate youtube videos for note-taking with org-mode. Any interop with this project? What are the differences?
https://github.com/kljohann/mpv.el/wiki

**Comment by isamert** [comment]
I haven't used mpv.el but seems like it's goal is more or less same with empv.el, which is being an Emacs interface for [mpv media player](https://mpv.io/). As far as I can tell, empv.el does a bit more by having YouTube interface, media management tools etc. and exposing more mpv functions, but at the same time I also see that some functions exposed by mpv.el is not exposed by empv.el.

If you decide to try empv.el and find some functionality missing that is present in mpv.el (or any other feature that you think it's relevant), raise an issue and we can add.

I didn't fully get the transcription workflow: I guess mpv.el provides some functionality so that you can jump to a point in video written on a buffer or insert the current playback time of a video to a buffer and this way it helps doing transcription stuff, right?

**Comment by isamert** [comment]
Hopefully this concludes it, let me know if you have more questions. I may add more in-dept comparison section to README if I ever try mpv.el in the future.
