### ISSUE TITLE
empv--let-properties

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#55]
Can you explain:

1. With a stream playing:
   #+begin_src 

(empv--let-properties '(time-pos )
  (format "%.2d" .time-pos))

(empv--let-properties '(time-pos )
  (message "%.2d" .time-pos))

   #+end_src
   1. The form using _message_ returns the time

   2.  The form using _format_ does not return the time.

**Comment by isamert** [comment]
Actually the form using `message` does not return time, it simply prints it at a _later_ time.

`empv--let-properties` is a macro and the body you sent to this macro is executed later, not immediately. Instead of reading the forms this way:

```elisp
(empv--let-properties '(time-pos)
  (format "%.2d" .time-pos))

(empv--let-properties '(time-pos )
  (message "%.2d" .time-pos))
```

You can read them like the following, for the sake of understanding:

```elisp
(empv--let-properties '(time-pos)
  (lambda (value) (format "%.2d" value)))

(empv--let-properties '(time-pos )
  (lambda (value) (message "%.2d" value)))
```

So the second parameter to the `empv--let-properties` is simply a callback function which is executed later at time when empv gets the `time-pos` value from mpv itself. Because the callback function is executed later at time, the return value of the callback function is never used anywhere and the value returned by format is discarded. But the other form, the one using `message` is again, executed later at time but it simply prints to the echo area and you are able to see the value for that reason.

**Comment by tvraman** [comment]
makes sense, thanks!
--
