### ISSUE TITLE
Create: Chapter And Bookmark Metadata

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#79]
* Feature Request: Chapter And Bookmarks For mp3

1. After some research, turns out that ffmpeg can be used to add chapter
and bookmarks to mp3 files. https://www.reddit.com/r/ffmpeg/comments/nyfx7a/is_there_a_correct_way_to_write_chapters_to_a_mp3/.rss
1. Lots of content on Youtube have such bookmarks and chapter marks.
2. Could we teach empv to:
   1. Add such bookmarks to local mp3 files?
   2. Update the downloader to preserve or recreate such marks if they
      were originally present?

**Comment by isamert** [comment]
> Update the downloader to preserve or recreate such marks if they
> were originally present?

I believe this is a good addition and probably `yt-dlp` already
supports this, a quick look revealed the `--embed-metadata` option,
which should include the metadata to files. Adding a variable for
yt-dlp options should do the trick (so that user can add
`--embed-metadata` and all downloaded files will have their
metadata. There seems to be other useful options for `yt-dlp` too,
like: `--embed-thumbnail` `--write-description` etc.)

> Add such bookmarks to local mp3 files?

I don't think this is in the scope of `empv`, at least I don't think
it would worth. Because we can simply get away with using
`--embed-metadata` for downloading files. If we had to somehow
manually extract and add metadata using ffmpeg then we could simply
expose the same function to work on local files but that will much
more work for a small feature.

**Comment by tvraman** [comment]
agreed  --- first pass: let's get the embedded metadata from YT when downloading
