### ISSUE TITLE
How to use on doom emacs 

### ISSUE THREAD

**Issue by v-Nyo** [isamert/empv.el#86]
Installed from melpa.
When I use empv-play-file it starts the video in the background (hear sound)  but I see no video output at all.
(the mpv process is launched with --no-video and --input-ipc-server=/tmp/empv-socket)
How is this package supposed to work?

**Comment by isamert** [comment]
So, this package is more audio-focused but it provides the means to
interact with videos too. If you want to see the video itself, you need
to call `empv-toggle-video`. Also see the `empv-display-current`
function to learn the progress about the current media empv is playing.

I recommend you taking a look at `empv-map` and binding it to a key so
that you have quick access to commands like this. See the "Keybindings"
section in the README. Of course, there are also lot's of other
functionality that is not present in this keymap. Just see the rest of
the README and take a look at the commands that starts with `empv-` when
you do `M-x`.

**Comment by isamert** [comment]
Hmm, there is no way to do this currently. Maybe I can define a variable
like:

    empv-automatically-view-videos

and when set to t, it switches to video view automatically.

But this has problems because:

- It does not handle the case where you start playing audio and it
  doesn't automatically toggle back to non-video mode.
- It doesn't handle YouTube videos. It can't know if you want to play
  them as audio or video unless you specify explicitly. (Of course they
  are technically videos but I mainly use the YouTube feature for
  listening music)

Maybe with these restrictions, I can add the mentioned variable. Do you
have another idea?

> Thanks wasn't really obvious in the README.

Thanks for the feedback, I'll see what I can do with the README in this
regard. Let me know if you have ideas on improving it.

**Comment by isamert** [comment]
Or maybe I can simply make this (opening the video directly) the default
behavior for `empv-play-video` and rest stays the same?
